/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazUsuario;

import javax.swing.JOptionPane;
import ClasesPrincipales.*;

/**
 *
 * @author Quincho
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfNombreUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfContraseñaUsuario = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        bIngresar = new javax.swing.JButton();
        cbTipoUsuario = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Iniciar Sesión");

        jLabel2.setText("Nombre de Usuario");

        jLabel3.setText("Contraseña");

        bIngresar.setText("Ingresar");
        bIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIngresarActionPerformed(evt);
            }
        });

        cbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Coordinador", "Estudiante", "Profesor" }));

        jLabel4.setText("Tipo de usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bIngresar))
                    .addComponent(tfNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfContraseñaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfContraseñaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(bIngresar))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static Controlador instancia = new Controlador();
    private static Usuario instaciau= new Usuario(null, null, null);
    private static Departamento instaciad= new Departamento(null);    
    private void bIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIngresarActionPerformed
        String nU = tfNombreUsuario.getText().toString();
        char[] cUC = tfContraseñaUsuario.getPassword();
        String cU = String.copyValueOf(cUC, 0, cUC.length);
        String tU = cbTipoUsuario.getSelectedItem().toString();
        
        Usuario u1 = new Usuario("leock123@gmail.com", "123", "Estudiante");
        instancia.insertarUsuario(u1);
        u1 = new Usuario("oscar@gmail.com", "123", "Profesor");
        instancia.insertarUsuario(u1);
        u1 = new Usuario("leo@gmail.com", "123", "Coordinador");
        instancia.insertarUsuario(u1);
        
        String resultado = instancia.validarUsuario(nU, cU, tU);
        
        
        if (resultado.equals("correcto")){
            this.setVisible(false);
            instancia.usuarioActual = nU;
            instancia.tipoUsuarioActual = tU;
            if (tU.equals("Coordinador")){
                insertardatos();
                new PaginaCoordinador().setVisible(true);
            }else if (tU.equals("Estudiante")){
                new PaginaEstudiante().setVisible(true);
            }else {
                new PaginaProfesor().setVisible(true);
            }
        }else if (resultado.equals("Tipo de Usuario Incorrecto")){
            JOptionPane.showConfirmDialog(this, resultado, "Usuario", 
                    JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showConfirmDialog(this, resultado, "Usuario", 
                    JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bIngresarActionPerformed

    public static void insertardatos(){
      //Inserciones de Semestres
      Semestre s1= new Semestre(1);
      instancia.insertarSemestre(s1);
      Semestre s2= new Semestre(2);
      instancia.insertarSemestre(s2);
      Semestre s3= new Semestre(3);
      instancia.insertarSemestre(s3);
      Semestre s4= new Semestre(4);
      instancia.insertarSemestre(s4);
      Semestre s5= new Semestre(5);
      instancia.insertarSemestre(s5);
      Semestre s6= new Semestre(6);
      instancia.insertarSemestre(s6);
      Semestre s7= new Semestre(7);
      instancia.insertarSemestre(s7);
      Semestre s8= new Semestre(8);
      instancia.insertarSemestre(s8);
        
      //Inserciones de departamentos
      Departamento d1=  new Departamento("Computación");
      instancia.insertarDepartamento(d1);
      Departamento d2=  new Departamento("Matemáticas");
      instancia.insertarDepartamento(d2);
      //Inserciones de profesores
      Profesor p1 = new Profesor("Oscar Viquez", "1-111-111","Computación","oscar@gmail.com","123");
      instancia.insertarProfesor(p1);
      Profesor p2 = new Profesor("Lorena Valerio", "1-211-111","Computación","lorena@gmail.com","123");
      instancia.insertarProfesor(p1);  
      //Inserciones de aulas
      AulaTeorica ate1= new AulaTeorica(true,true,1, "Aula1", "Primer piso", 30);
      instancia.insertarAulaTeorica(ate1);
      AulaTeorica ate2= new AulaTeorica(true,true,2, "Aula2", "Primer piso", 30);
      instancia.insertarAulaTeorica(ate2);  
      AulaTeorica ate3= new AulaTeorica(true,true,3, "Aula3", "Primer piso", 30);
      instancia.insertarAulaTeorica(ate3);
      
      Laboratorio l1= new Laboratorio(1, "Proyector", 1, "Lab 1", "Laboratorios", 24);
      instancia.insertarLaboratorio(l1);
      Laboratorio l2= new Laboratorio(2, "Proyector", 2, "Lab 2", "Laboratorios", 24);
      instancia.insertarLaboratorio(l2);
      //Inserciones de Asignatura Practica
      
      AsignaturaPractica ap1= new AsignaturaPractica("Practica.doc", "Win 7", "Introducción a la Programación", 4, 12, "Carrera");
      instancia.insertarAsignaturaPractica(ap1);
      AsignaturaPractica ap2= new AsignaturaPractica("Practica1.doc", "Win 7", "Taller", 4, 12, "Carrera");
      instancia.insertarAsignaturaPractica(ap2);
      AsignaturaPractica ap3= new AsignaturaPractica("Ejercicio.doc", "Win 7", "Calculo", 4, 12, "Servicio");
      instancia.insertarAsignaturaPractica(ap3);
      
      //Inserciones de Asignatura Teorica
      
      AsignaturaTeorica at1= new AsignaturaTeorica("www.ayuda.com","Computación y Sociedad" , 4, 12, "Servicio");
      instancia.insertarAsignaturaTeorica(at1);
      AsignaturaTeorica at2= new AsignaturaTeorica("www.ayuda.com","Administración de Proyectos" , 4, 12, "Servicio");
      instancia.insertarAsignaturaTeorica(at2);
      AsignaturaTeorica at3= new AsignaturaTeorica("www.ayuda.com","Aseguramiento de la Calidad" , 4, 12, "Servicio");
      instancia.insertarAsignaturaTeorica(at3);
    
      //Inserciones de Grupos
      
      //Grupo g1= new Grupo("50", at3, p2);
      //Grupo g2= new Grupo("51", at2, p1);
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                
                insertardatos();
                //Controlador ins = new Controlador();
                instancia.insertarCursosSemestre();
                //insertarCantidadSemestres(8);
            }
        });
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bIngresar;
    private javax.swing.JComboBox cbTipoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField tfContraseñaUsuario;
    private javax.swing.JTextField tfNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
