/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazUsuario;

import static javax.swing.JFrame.EXIT_ON_CLOSE;

/**
 *
 * @author Quincho
 */
public class PaginaProfesor extends javax.swing.JFrame {

    /**
     * Creates new form PaginaProfesor
     */
    public PaginaProfesor() {
        
        initComponents();
  //  MA.setVisible(false);
   // jTextField5.setVisible(false);
  //  SO.setVisible(false);
   // jTextField6.setVisible(false);
    asigpractica.setVisible(false);
     asigteo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        lNombreUsuario = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lTipoUsuario = new javax.swing.JLabel();
        asigpractica = new javax.swing.JPanel();
        SO = new javax.swing.JLabel();
        mat = new javax.swing.JTextField();
        PW = new javax.swing.JLabel();
        op = new javax.swing.JTextField();
        cred = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        horasd = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        asigteo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nom1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cred1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        horasd1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cat1 = new javax.swing.JTextField();
        op1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        MA = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel7.setText("Bienvenido: ");

        lNombreUsuario.setText(" ");

        jLabel8.setText("Usuario:");

        lTipoUsuario.setText(" ");

        asigpractica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SO.setText("Sistema Operativo");
        asigpractica.add(SO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        mat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matActionPerformed(evt);
            }
        });
        asigpractica.add(mat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 118, -1));

        PW.setText("Página Web");
        asigpractica.add(PW, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        op.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opActionPerformed(evt);
            }
        });
        asigpractica.add(op, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 118, -1));

        cred.setMinimumSize(new java.awt.Dimension(20, 20));
        cred.setName(""); // NOI18N
        asigpractica.add(cred, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 118, -1));

        jLabel2.setText("Créditos");
        asigpractica.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });
        asigpractica.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 118, -1));

        jLabel1.setText("Nombre");
        asigpractica.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel4.setText("Categoria");
        asigpractica.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        asigpractica.add(cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 118, -1));

        jLabel3.setText("Horas Dedicación");
        asigpractica.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        asigpractica.add(horasd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 118, -1));

        jButton1.setText(">");
        asigpractica.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, -1));

        jButton2.setText("<");
        asigpractica.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        jButton3.setText("Modificar");
        asigpractica.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        asigteo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Nombre");
        asigteo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        nom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom1ActionPerformed(evt);
            }
        });
        asigteo.add(nom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 118, -1));

        jLabel6.setText("Créditos");
        asigteo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        cred1.setMinimumSize(new java.awt.Dimension(20, 20));
        cred1.setName(""); // NOI18N
        asigteo.add(cred1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 118, -1));

        jLabel9.setText("Horas Dedicación");
        asigteo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        asigteo.add(horasd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 118, -1));

        jLabel10.setText("Categoria");
        asigteo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        asigteo.add(cat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 118, -1));

        op1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op1ActionPerformed(evt);
            }
        });
        asigteo.add(op1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 118, -1));

        jButton4.setText("<");
        asigteo.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        jButton5.setText(">");
        asigteo.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, -1));

        MA.setText("Material Apoyo");
        asigteo.add(MA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jButton6.setText("Modificar");
        asigteo.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        jMenu1.setText("Asignatura");

        jMenuItem1.setText("Práctica");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Teórica");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Horario");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(lNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lTipoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(152, 152, 152))
            .addGroup(layout.createSequentialGroup()
                .addComponent(asigpractica, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(asigteo, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addGap(5, 5, 5)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lNombreUsuario)
                    .addComponent(jLabel8)
                    .addComponent(lTipoUsuario))
                .addGap(27, 27, 27)
                .addComponent(asigpractica, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(26, Short.MAX_VALUE)
                    .addComponent(asigteo, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cargarInformacion();// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void matActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matActionPerformed

    private void opActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opActionPerformed

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        asigteo.setVisible(false);
        asigpractica.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void nom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom1ActionPerformed

    private void op1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        asigpractica.setVisible(false);
        asigteo.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaProfesor().setVisible(true);
            }
        });
    }
    
    public void cargarInformacion(){
        lNombreUsuario.setText(Login.instancia.usuarioActual);
        lTipoUsuario.setText(Login.instancia.tipoUsuarioActual);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MA;
    private javax.swing.JLabel PW;
    private javax.swing.JLabel SO;
    private javax.swing.JPanel asigpractica;
    private javax.swing.JPanel asigteo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cat;
    private javax.swing.JTextField cat1;
    private javax.swing.JTextField cred;
    private javax.swing.JTextField cred1;
    private javax.swing.JTextField horasd;
    private javax.swing.JTextField horasd1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lNombreUsuario;
    private javax.swing.JLabel lTipoUsuario;
    private javax.swing.JTextField mat;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField nom1;
    private javax.swing.JTextField op;
    private javax.swing.JTextField op1;
    // End of variables declaration//GEN-END:variables
}
