/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazUsuario;

import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.*;

/**
 *
 * @author Quincho
 */
public class PaginaProfesor extends javax.swing.JFrame {

    /**
     * Creates new form PaginaProfesor
     */
    public PaginaProfesor() {
        
        initComponents();
  //  MA.setVisible(false);
   // jTextField5.setVisible(false);
  //  SO.setVisible(false);
   // jTextField6.setVisible(false);
    asigpractica.setVisible(false);
     asigteo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lNombreUsuario = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lTipoUsuario = new javax.swing.JLabel();
        asigpractica = new javax.swing.JPanel();
        SO = new javax.swing.JLabel();
        mat = new javax.swing.JTextField();
        PW = new javax.swing.JLabel();
        op = new javax.swing.JTextField();
        cred = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        horasd = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        cbpracticas = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        cbDia = new javax.swing.JComboBox();
        cbHoraInicio = new javax.swing.JComboBox();
        cbHoraFinal = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jButton7 = new javax.swing.JButton();
        asigteo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nom1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cred1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        horasd1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cat1 = new javax.swing.JTextField();
        op1 = new javax.swing.JTextField();
        MA = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        cbteoricas = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        cbDia1 = new javax.swing.JComboBox();
        cbHoraInicio1 = new javax.swing.JComboBox();
        cbHoraFinal1 = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jDialog1.setMinimumSize(new java.awt.Dimension(300, 200));

        jLabel13.setText("Modificado con Exito!!!");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel13))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jButton1)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel13)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel7.setText("Bienvenido: ");

        lNombreUsuario.setText(" ");

        jLabel8.setText("Usuario:");

        lTipoUsuario.setText(" ");

        asigpractica.setMinimumSize(new java.awt.Dimension(550, 280));
        asigpractica.setName(""); // NOI18N
        asigpractica.setPreferredSize(new java.awt.Dimension(550, 280));
        asigpractica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SO.setText("Sistema Operativo");
        asigpractica.add(SO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        mat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matActionPerformed(evt);
            }
        });
        asigpractica.add(mat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 118, -1));

        PW.setText("Página Web");
        asigpractica.add(PW, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        op.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opActionPerformed(evt);
            }
        });
        asigpractica.add(op, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 118, -1));

        cred.setMinimumSize(new java.awt.Dimension(20, 20));
        cred.setName(""); // NOI18N
        asigpractica.add(cred, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 118, -1));

        jLabel2.setText("Créditos");
        asigpractica.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });
        asigpractica.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 118, -1));

        jLabel1.setText("Nombre");
        asigpractica.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel4.setText("Categoria");
        asigpractica.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        asigpractica.add(cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 118, -1));

        jLabel3.setText("Horas Dedicación");
        asigpractica.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        asigpractica.add(horasd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 118, -1));

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        asigpractica.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        cbpracticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbpracticasActionPerformed(evt);
            }
        });
        asigpractica.add(cbpracticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 120, -1));

        jLabel11.setText("Seleccione el curso");
        asigpractica.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        cbDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lunes", "Martes", "Miercoles", "Jueves", "Viernes" }));
        asigpractica.add(cbDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        cbHoraInicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "7:00", "7:55", "8:50", "9:45", "10:40", "12:30", "1:25", "2:20", "3:15" }));
        cbHoraInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHoraInicioActionPerformed(evt);
            }
        });
        asigpractica.add(cbHoraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, -1));

        asigpractica.add(cbHoraFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        jLabel14.setText("Hora Finalización");
        asigpractica.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        jLabel15.setText("Hora Inicio");
        asigpractica.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 80, 20));

        jLabel16.setText("Dia");
        asigpractica.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        jLabel17.setText("Horario del Curso");
        asigpractica.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        asigpractica.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 10, 220));
        asigpractica.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 550, -1));

        jButton7.setText("Salir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        asigteo.setMinimumSize(new java.awt.Dimension(450, 270));
        asigteo.setPreferredSize(new java.awt.Dimension(550, 270));
        asigteo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Nombre");
        asigteo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        nom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom1ActionPerformed(evt);
            }
        });
        asigteo.add(nom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 118, -1));

        jLabel6.setText("Créditos");
        asigteo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        cred1.setMinimumSize(new java.awt.Dimension(20, 20));
        cred1.setName(""); // NOI18N
        asigteo.add(cred1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 118, -1));

        jLabel9.setText("Horas Dedicación");
        asigteo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        asigteo.add(horasd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 118, -1));

        jLabel10.setText("Categoria");
        asigteo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        asigteo.add(cat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 118, -1));

        op1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op1ActionPerformed(evt);
            }
        });
        asigteo.add(op1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 118, -1));

        MA.setText("Material Apoyo");
        asigteo.add(MA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 20));

        jButton6.setText("Modificar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        asigteo.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        cbteoricas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbteoricasActionPerformed(evt);
            }
        });
        asigteo.add(cbteoricas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 120, -1));

        jLabel12.setText("Seleccione el curso");
        asigteo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        cbDia1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lunes", "Martes", "Miercoles", "Jueves", "Viernes" }));
        asigteo.add(cbDia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        cbHoraInicio1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "7:00", "7:55", "8:50", "9:45", "10:40", "12:30", "1:25", "2:20", "3:15" }));
        cbHoraInicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHoraInicio1ActionPerformed(evt);
            }
        });
        asigteo.add(cbHoraInicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, -1));

        asigteo.add(cbHoraFinal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        jLabel18.setText("Hora Finalización");
        asigteo.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        jLabel19.setText("Hora Inicio");
        asigteo.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 80, 20));

        jLabel20.setText("Dia");
        asigteo.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        jLabel21.setText("Horario del Curso");
        asigteo.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        asigteo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 10, 190));
        asigteo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 550, -1));

        jMenu1.setText("Asignatura");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Práctica");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Teórica");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(lNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lTipoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(79, 79, 79)
                .addComponent(jButton7))
            .addGroup(layout.createSequentialGroup()
                .addComponent(asigpractica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 5, Short.MAX_VALUE)
                    .addComponent(asigteo, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 5, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lNombreUsuario)
                    .addComponent(jLabel8)
                    .addComponent(lTipoUsuario)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addComponent(asigpractica, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addGap(15, 15, 15))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 49, Short.MAX_VALUE)
                    .addComponent(asigteo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 50, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 int i=0; //asignatura teorica

  //int x=y;//practica
  int z= i;//teorica
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cargarInformacion();// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void matActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matActionPerformed

    private void opActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opActionPerformed

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         Boolean v= false;  
         v= true;
          if (v= true);
     {
     cbpracticas.removeAllItems();
     }
        try{ 
       // practicas.removeAllItems();
           
        asigteo.setVisible(false);
        asigpractica.setVisible(true);
        v=true;
       
      
        for(int i=0; i<Login.instancia.getlistaasignaturap().size(); i++ ){
        cbpracticas.addItem(Login.instancia.getlistaasignaturap().get(i).getNombre());
        }
       
       // teoricas.removeAllItems();
       }catch(IndexOutOfBoundsException e){
       System.out.printf(e.getMessage());
       }
     cbteoricas.removeAllItems();    
     
    
     
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void nom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom1ActionPerformed

    private void op1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       Boolean v= false;  
         v= true;
          if (v= true);
     {
     cbteoricas.removeAllItems();
     }
        try{
        asigpractica.setVisible(false);
        asigteo.setVisible(true);
        
         for(int i=0; i<Login.instancia.getlistaasignaturat().size(); i++ ){
        cbteoricas.addItem(Login.instancia.getlistaasignaturat().get(i).getNombre());
        }

         //practicas.removeAllItems();
    }catch (IndexOutOfBoundsException e){
       System.out.printf(e.getMessage());
       }
        
        cbpracticas.removeAllItems();
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed
     
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void cbpracticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbpracticasActionPerformed

      try{
       nom.setText(Login.instancia.getlistaasignaturap().get(cbpracticas.getSelectedIndex()).getNombre());
       cred.setText(String.valueOf(Login.instancia.getlistaasignaturap().get(cbpracticas.getSelectedIndex()).getNumeroCreditos())); 
       horasd.setText(String.valueOf(Login.instancia.getlistaasignaturap().get(cbpracticas.getSelectedIndex()).getHorasDedicadas()));
       cat.setText(Login.instancia.getlistaasignaturap().get(cbpracticas.getSelectedIndex()).getCategoriaCurso());
       mat.setText(Login.instancia.getlistaasignaturap().get(cbpracticas.getSelectedIndex()).getMaterialApollo());
       op.setText(Login.instancia.getlistaasignaturap().get(cbpracticas.getSelectedIndex()).getSistemaOperativo());
       cbDia.setSelectedItem(Login.instancia.getlistagrupo().get(cbpracticas.getSelectedIndex()).getHorario().getDia());
       cbHoraInicio.setSelectedItem(Login.instancia.getlistagrupo().get(cbpracticas.getSelectedIndex()).getHorario().getHoraInicio()); 
       cbHoraFinal.setSelectedItem(Login.instancia.getlistagrupo().get(cbpracticas.getSelectedIndex()).getHorario().getHoraFinal());
      }catch(IndexOutOfBoundsException e){
      System.out.printf(e.getMessage());
      }
    }//GEN-LAST:event_cbpracticasActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void cbteoricasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbteoricasActionPerformed
        try{   
        nom1.setText(Login.instancia.getlistaasignaturat().get(cbteoricas.getSelectedIndex()).getNombre()); 
        cred1.setText(String.valueOf(Login.instancia.getlistaasignaturat().get(cbteoricas.getSelectedIndex()).getNumeroCreditos())); 
        horasd1.setText(String.valueOf(Login.instancia.getlistaasignaturat().get(cbteoricas.getSelectedIndex()).getHorasDedicadas()));
        cat1.setText(Login.instancia.getlistaasignaturat().get(cbteoricas.getSelectedIndex()).getCategoriaCurso());
        op1.setText(Login.instancia.getlistaasignaturat().get(cbteoricas.getSelectedIndex()).getPagina());
        cbDia1.setSelectedItem(Login.instancia.getlistagrupo().get(cbteoricas.getSelectedIndex()).getHorario().getDia());
        cbHoraInicio1.setSelectedItem(Login.instancia.getlistagrupo().get(cbteoricas.getSelectedIndex()).getHorario().getHoraInicio()); 
        cbHoraFinal1.setSelectedItem(Login.instancia.getlistagrupo().get(cbteoricas.getSelectedIndex()).getHorario().getHoraFinal());
        }catch(IndexOutOfBoundsException e){
      System.out.printf(e.getMessage());
      }
    }//GEN-LAST:event_cbteoricasActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

 Login.instancia.modificarasigpractica(mat.getText(),op.getText(), nom.getText() , Integer.parseInt(cred.getText()), 
         Integer.parseInt(horasd.getText()), cat.getText(),cbDia.getSelectedItem().toString(),
         cbHoraInicio.getSelectedItem().toString(),cbHoraFinal.getSelectedItem().toString());
       
 jDialog1.setVisible(true);
this.dispose();
 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
 Login.instancia.modificarasigteorica(op1.getText(), nom1.getText() , Integer.parseInt(cred1.getText()), 
         Integer.parseInt(horasd1.getText()), cat1.getText(),cbDia1.getSelectedItem().toString(),
         cbHoraInicio1.getSelectedItem().toString(),cbHoraFinal1.getSelectedItem().toString());
      
 jDialog1.setVisible(true);
 this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//new PaginaProfesor().setVisible(true);  
this.setVisible(true);
jDialog1.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbHoraInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHoraInicioActionPerformed
        String arregloHoras[] = {"7:50", "8:45", "9:40", "10:35", "11:30",
            "1:20", "2:15", "3:10", "4:05"};
        cbHoraFinal.removeAllItems();
        for (int i = cbHoraInicio.getSelectedIndex(), l = arregloHoras.length;
            i < l; i++){
            cbHoraFinal.addItem(arregloHoras[i]);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cbHoraInicioActionPerformed

    private void cbHoraInicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHoraInicio1ActionPerformed
        String arregloHoras[] = {"7:50", "8:45", "9:40", "10:35", "11:30",
            "1:20", "2:15", "3:10", "4:05"};
        cbHoraFinal1.removeAllItems();
        for (int i = cbHoraInicio1.getSelectedIndex(), l = arregloHoras.length;
            i < l; i++){
            cbHoraFinal1.addItem(arregloHoras[i]);
        }  // TODO add your handling code here:
    }//GEN-LAST:event_cbHoraInicio1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaProfesor().setVisible(true);
            }
        });
    }
    
    public void cargarInformacion(){
        lNombreUsuario.setText(Login.instancia.usuarioActual);
        lTipoUsuario.setText(Login.instancia.tipoUsuarioActual);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MA;
    private javax.swing.JLabel PW;
    private javax.swing.JLabel SO;
    private javax.swing.JPanel asigpractica;
    private javax.swing.JPanel asigteo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cat;
    private javax.swing.JTextField cat1;
    private javax.swing.JComboBox cbDia;
    private javax.swing.JComboBox cbDia1;
    private javax.swing.JComboBox cbHoraFinal;
    private javax.swing.JComboBox cbHoraFinal1;
    private javax.swing.JComboBox cbHoraInicio;
    private javax.swing.JComboBox cbHoraInicio1;
    private javax.swing.JComboBox cbpracticas;
    private javax.swing.JComboBox cbteoricas;
    private javax.swing.JTextField cred;
    private javax.swing.JTextField cred1;
    private javax.swing.JTextField horasd;
    private javax.swing.JTextField horasd1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lNombreUsuario;
    private javax.swing.JLabel lTipoUsuario;
    private javax.swing.JTextField mat;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField nom1;
    private javax.swing.JTextField op;
    private javax.swing.JTextField op1;
    // End of variables declaration//GEN-END:variables
}
